version: "3.9"

networks:
  web:
    name: web
    external: true

volumes: {}

services:
  prometheus:
    image: ${PROMETHEUS_TAG}
    restart: always
    networks:
      - web
    volumes:
      - ./web.yml:/etc/prometheus/web.yml:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_HOST}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus.middlewares=prometheus-auth"
      - "traefik.http.middlewares.prometheus-auth.basicauth.users=${PROMETHEUS_\
        HTTP_BASIC_AUTH}"
