apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-letsencrypt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager-letsencrypt
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kube/infrastructure/cert-manager-letsencrypt
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}