.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rust-cli-template 1  "rust-cli-template 0.1.0" 
.SH NAME
rust\-cli\-template \- A CLI app template
.SH SYNOPSIS
\fBrust\-cli\-template\fR [\fB\-n\fR|\fB\-\-name\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
A CLI app template
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR=\fINAME\fR [default: World]
The name of the user
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
.SH AUTHORS
Raphael Peters <rappet@rappet.de>
