.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH rust-rest-server-template 1  "rust-rest-server-template 0.1.0" 
.SH NAME
rust\-rest\-server\-template \- A REST server template
.SH SYNOPSIS
\fBrust\-rest\-server\-template\fR [\fB\-p\fR|\fB\-\-http\-port\fR] [\fB\-a\fR|\fB\-\-http\-address\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
A REST server template
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-http\-port\fR=\fIHTTP_PORT\fR [default: 8080]
Port of the HTTP server
.TP
\fB\-a\fR, \fB\-\-http\-address\fR=\fIHTTP_ADDRESS\fR [default: ::1]
Address to listen on (`0.0.0.0`/`::` or `127.0.0.1`/`::1`)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
.SH AUTHORS
Raphael Peters <rappet@rappet.de>
