{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: {{ .Values.spec.project | quote }}
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.16.2
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
{{- end }}