apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-inwx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: cert-manager-webhook-inwx
    repoURL: https://smueller18.gitlab.io/helm-charts
    targetRevision: 0.5.0
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true