{{- if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: {{ .Values.spec.project | quote }}
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.3.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 14d
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 2Gi
          ingress:
            enabled: true
            ingressClassName: {{.Values.ingressClassName | quote}}
            annotations:
              cert-manager.io/cluster-issuer: {{.Values.clusterIssuer | quote}}
            hosts:
              - {{.Values.prometheus.prometheusDomain | quote}}
            paths:
              - /
            pathType: ImplementationSpecific
            tls:
              - hosts:
                  - {{.Values.prometheus.prometheusDomain | quote}}
                secretName: tls-certificate-prometheus
        grafana:
          enabled: true
          defaultDashboardsEditable: false
          ingress:
            enabled: true
            ingressClassName: {{.Values.ingressClassName | quote}}
            annotations:
              cert-manager.io/cluster-issuer: {{.Values.clusterIssuer | quote}}
            hosts:
              - {{.Values.prometheus.grafanaDomain}}
            paths:
              - /
            pathType: ImplementationSpecific
            tls:
              - hosts:
                  - {{.Values.prometheus.grafanaDomain}}
                secretName: tls-certificate-grafana
{{- end }}