apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 66.3.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            retention: 14d
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 2Gi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.rappet-home.de
            paths:
              - /
            pathType: ImplementationSpecific
            tls:
              - hosts:
                  - "*.rappet-home.de"
        grafana:
          enabled: true
          defaultDashboardsEditable: false
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.rappet-home.de
            paths:
              - /
            pathType: ImplementationSpecific
            tls:
              - hosts:
                  - "*.rappet-home.de"