{{- if .Values.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: {{ .Values.spec.project | quote }}
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    targetRevision: 2.17.0
    helm:
      valuesObject: {}
{{- end }}