apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-clusterissuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project | quote }}
  source:
    path: infra/kube/cert-manager-clusterissuers
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
