global:
  checkNewVersion: true
  sendAnonymousUsage: false

experimental:
  http3: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443
    enablehttp3: true

api:
  insecure: true

providers:
  docker: {}

# ACME configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "test-acme@rappet.de"
      storage: "/acme/acme.json"
      tlsChallenge: {}
