apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-world
  annotations:
    cert-manager.io/cluster-issuer: "{{.Values.clusterIssuer}}"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: {{.Values.ingressClassName}}
  tls:
    - hosts:
        - "{{.Values.domain}}"
      secretName: tls-certificate
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-hello-world
            port: 
              number: 80