apiVersion: v2
name: cert-manager
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cert-manager
    version: 1.16.2
    repository: https://charts.jetstack.io
  - name: cert-manager-webhook-inwx
    version: 0.5.0
    repository: https://smueller18.gitlab.io/helm-charts