spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rappet/stash
    targetRevision: HEAD
  project: default

ingressClassName: traefik
clusterIssuer: letsencrypt-dns-prod

ingressNginx:
  enabled: false

certManager:
  enabled: true
  letsEncrypt:
    enabled: true
  inwx:
    enabled: true
  hetzner:
    enabled: true

reflector:
  # currently not used
  enabled: false

prometheus:
  enabled: true
  prometheusDomain: prometheus.rappet.xyz
  grafanaDomain: grafana.rappet.xyz

postgres:
  enabled: true

emqx:
  enabled: false
