apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-world
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
      secretName: ingress-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-hello-world
            port: 
              number: 80