version: "3.9"
services:
  # Reverse Proxy
  traefik:
    image: ${TRAEFIK_TAG}
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/traefik/acme:/acme
    networks:
      - web
  #  labels:
  #    - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) && PathPrefix(`/`)"
  #    - "traefik.http.routers.dashboard.service=dashboard@internal"
  #    - "traefik.http.routers.dashboard.tls=true"
  #    - "traefik.http.routers.api.rule=Host(`traefik.localhost`) && PathPrefix(`/api`)"
  #    - "traefik.http.routers.api.service=api@internal"
  #    - "traefik.http.routers.api.tls=true"


  gitea:
    image: ${GITEA_TAG}
    env_file: ${GITEA_ENV}
    restart: always
    networks:
      - web
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_SSH_PORT}:22"
    labels:
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_HOST}`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"

  drone:
    image: drone/drone:2
    restart: always
    environment:
      DRONE_GITEA_SERVER: ${DRONE_GITEA_SERVER}
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
    networks:
      - web
    volumes:
      - ./data/drone:/data
    labels:
      - "traefik.http.routers.drone.rule=Host(`${DRONE_HOST}`)"
      - "traefik.http.services.drone.loadbalancer.server.port=80"
      - "traefik.http.routers.drone.tls=true"
      - "traefik.http.routers.drone.tls.certresolver=letsencrypt"
networks:
  web:

    null
volumes:
  gitea: null
